swagger: '2.0'
info:
  title: Chronicler API
  # description: Events something
  version: "1.0.0"
# the domain of the service
host: localhost:8080
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /api/v1/
produces:
  - application/json
paths:
  /events:
    get:
      summary: Get all events
      responses:
        200:
         description: A list of all events in the given Chronicle
         schema:
           type: array
           items:
             $ref: '#/definitions/Event'
    post:
      summary: Post a new event
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Event'

definitions:
  Event:
    type: object
    properties:
      id:
        type: string
        description: yadda yadda id
      page:
        type: number
        description: Which page in the Chronicle this event has
