server:
  rootPath: '/api/*'
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081
  requestLog:
    appenders: []

swagger:
  resourcePackage: com.richodemus.chronicler.server.api.api
